# Generated by Django 4.2.9 on 2024-01-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everest_broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveddata',
            name='data',
            field=models.TextField(),
        ),
    ]
